jobs:
- name: harvester maintain run
  command: powershell -ExecutionPolicy Bypass -File "D:\Github\blue-harvest\maintenance.ps1"
  enabled: true
  schedule:
    unit: days
    every: 1
    at: 01:00
- name: test venv job
  command: powershell -ExecutionPolicy Bypass -File "D:\Github\blue-harvest\test_venv.ps1"
  enabled: false
  schedule:
    unit: minutes
    every: 1
- name: harvester maintain monthly
  command: powershell -ExecutionPolicy Bypass -File "D:\Github\blue-harvest\maintenance-monthly.ps1"
  enabled: true
  schedule:
    unit: months
    at: 02:00
    day_of_month: 1
- name: harvester maintain quarterly
  command: powershell -ExecutionPolicy Bypass -File "D:\Github\blue-harvest\maintenance-quarterly.ps1"
  enabled: true
  schedule:
    unit: months
    at: 03:00
    day_of_month: 1
    months:
    - 1
    - 4
    - 7
    - 10
